In [37]:
import numpy as np


In [38]:
arr1 = np.random.randint(1,10,size=(3,3))
arr1

array([[2, 3, 9],
       [9, 9, 2],
       [5, 9, 1]])

In [39]:
vals,vectors = np.linalg.eig(arr1)


In [40]:
vals

array([16.7449223 +0.j        , -2.37246115+3.58117067j,
       -2.37246115-3.58117067j])

In [41]:
vectors

array([[ 0.47368242+0.j        ,  0.73957945+0.j        ,
         0.73957945-0.j        ],
       [ 0.69133585+0.j        , -0.48226219-0.21629709j,
        -0.48226219+0.21629709j],
       [ 0.54560032+0.j        , -0.19855509+0.3663835j ,
        -0.19855509-0.3663835j ]])

In [42]:
np.savetxt('eigen.csv',np.column_stack((vals,vectors)),delimiter = ',',header = 'values,vectors1')