In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1,20,size=(4,2))
arr1

array([[ 2,  9],
       [ 6, 11],
       [13,  2],
       [ 1,  2]])

In [3]:
arr2 = np.random.randint(1,20,size=(2,3))
arr2

array([[13,  4,  2],
       [ 1, 14, 18]])

In [4]:
arr_mul = np.matmul(arr1,arr2)
arr_mul

array([[ 35, 134, 166],
       [ 89, 178, 210],
       [171,  80,  62],
       [ 15,  32,  38]])

In [5]:
arr_transposed = arr_mul.T
arr_transposed

array([[ 35,  89, 171,  15],
       [134, 178,  80,  32],
       [166, 210,  62,  38]])