In [43]:
import numpy as np


In [44]:
arr1 = np.arange(1,21)
arr1
    

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
arr1_reshaped = arr1.reshape((4,5))
arr1_reshaped


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [46]:
arr1_flattened = arr1_reshaped.flatten()
arr1_flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
arr = np.random.randint(1,10,size=(3,3))
arr

array([[4, 3, 6],
       [8, 6, 9],
       [6, 7, 7]])

In [48]:
arr_transpose = arr.T
arr_transpose

array([[4, 8, 6],
       [3, 6, 7],
       [6, 9, 7]])

In [49]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [52]:
a2 = np.array([[1,2,3,4,5],[6,7,8,9,1]])
a2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1]])

In [54]:
a3 = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
a3

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [61]:
def function(arr):
    print(arr.ndim)
    print(arr.shape)
    print(arr.dtype)
    print(arr.size)

In [62]:
function(a1)

1
(5,)
int32
5


In [63]:
function(a2)

2
(2, 5)
int32
10


In [64]:
function(a3)

3
(3, 2, 5)
int32
30


In [65]:
b1 = np.array([1.1,2.2,3.3,4.4,5.5])
b1

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [66]:
b2 = np.array([True,False,False,True])
b2

array([ True, False, False,  True])

In [67]:
b3 = np.array([1,2,3,4,5])
b3

array([1, 2, 3, 4, 5])

In [68]:
def function1(arr):
    print(arr.itemsize)
    print(arr.nbytes)

In [69]:
function1(b1)

8
40


In [70]:
function1(b2)

1
4


In [73]:
function1(b3)

4
20


In [76]:
b1_to_int = b1.astype(np.int16)
b1_to_int

array([1, 2, 3, 4, 5], dtype=int16)

In [77]:
function1(b1_to_int)

2
10
